from mock_server.models import (
    Application,
    Category,
    IssueStatus,
    PipelineIssue,
    SecurityIssue,
    Severity,
)

MOCK_ISSUES: list[SecurityIssue] = [
    SecurityIssue(
        id="ISS-001",
        title="SQL Injection in user search endpoint",
        severity=Severity.CRITICAL,
        category=Category.INJECTION,
        status=IssueStatus.OPEN,
        cve_id="CVE-2024-1234",
        application="user-service",
        description="Unsanitized input in /api/users/search allows attackers to dump the users table.",
        discovered_at="2024-11-01",
    ),
    SecurityIssue(
        id="ISS-002",
        title="Reflected XSS in error page",
        severity=Severity.HIGH,
        category=Category.XSS,
        status=IssueStatus.OPEN,
        cve_id=None,
        application="frontend-app",
        description="The 404 error page reflects unescaped query parameters, enabling script injection.",
        discovered_at="2024-11-05",
    ),
    SecurityIssue(
        id="ISS-003",
        title="Broken authentication on password reset",
        severity=Severity.CRITICAL,
        category=Category.BROKEN_AUTH,
        status=IssueStatus.OPEN,
        cve_id=None,
        application="auth-service",
        description="Password reset tokens do not expire and can be replayed to take over any account.",
        discovered_at="2024-11-08",
    ),
    SecurityIssue(
        id="ISS-004",
        title="PII exposed in API response",
        severity=Severity.HIGH,
        category=Category.EXPOSED_DATA,
        status=IssueStatus.IN_PROGRESS,
        cve_id=None,
        application="api-gateway",
        description="The /api/users endpoint returns full SSN and date-of-birth for all users.",
        discovered_at="2024-11-10",
    ),
    SecurityIssue(
        id="ISS-005",
        title="Log4Shell vulnerability in payment service",
        severity=Severity.CRITICAL,
        category=Category.DEPENDENCY,
        status=IssueStatus.OPEN,
        cve_id="CVE-2021-44228",
        application="payment-service",
        description="log4j 2.14.1 is in use. Remote code execution via JNDI lookup is possible.",
        discovered_at="2024-11-12",
    ),
    SecurityIssue(
        id="ISS-006",
        title="S3 bucket publicly accessible",
        severity=Severity.MEDIUM,
        category=Category.MISCONFIG,
        status=IssueStatus.OPEN,
        cve_id=None,
        application="data-pipeline",
        description="The raw-ingest S3 bucket has a public ACL allowing unauthenticated reads.",
        discovered_at="2024-11-14",
    ),
    SecurityIssue(
        id="ISS-007",
        title="Command injection in report generator",
        severity=Severity.HIGH,
        category=Category.INJECTION,
        status=IssueStatus.RESOLVED,
        cve_id=None,
        application="reporting-service",
        description="Report filenames were passed unescaped to a shell command. Now fixed.",
        discovered_at="2024-10-20",
    ),
    SecurityIssue(
        id="ISS-008",
        title="Stored XSS in admin notes field",
        severity=Severity.MEDIUM,
        category=Category.XSS,
        status=IssueStatus.OPEN,
        cve_id=None,
        application="admin-portal",
        description="Admin notes are rendered without sanitization, allowing stored XSS for any admin viewer.",
        discovered_at="2024-11-16",
    ),
    SecurityIssue(
        id="ISS-009",
        title="Sensitive PII in application logs",
        severity=Severity.HIGH,
        category=Category.EXPOSED_DATA,
        status=IssueStatus.IN_PROGRESS,
        cve_id=None,
        application="user-service",
        description="Full credit card numbers appear in INFO-level logs, persisted to Splunk.",
        discovered_at="2024-11-18",
    ),
    SecurityIssue(
        id="ISS-010",
        title="Weak session token entropy",
        severity=Severity.MEDIUM,
        category=Category.BROKEN_AUTH,
        status=IssueStatus.OPEN,
        cve_id=None,
        application="api-gateway",
        description="Session tokens are generated with 32-bit random seed, making brute-force feasible.",
        discovered_at="2024-11-20",
    ),
]

MOCK_APPLICATIONS: list[Application] = [
    Application(
        id="APP-001",
        name="user-service",
        risk_score=8.5,
        issue_count=3,
        critical_count=1,
        last_scan="2024-11-20",
    ),
    Application(
        id="APP-002",
        name="auth-service",
        risk_score=9.2,
        issue_count=2,
        critical_count=1,
        last_scan="2024-11-20",
    ),
    Application(
        id="APP-003",
        name="payment-service",
        risk_score=9.8,
        issue_count=1,
        critical_count=1,
        last_scan="2024-11-19",
    ),
    Application(
        id="APP-004",
        name="frontend-app",
        risk_score=6.3,
        issue_count=2,
        critical_count=0,
        last_scan="2024-11-20",
    ),
    Application(
        id="APP-005",
        name="api-gateway",
        risk_score=7.1,
        issue_count=2,
        critical_count=0,
        last_scan="2024-11-20",
    ),
]

MOCK_PIPELINE_ISSUES: list[PipelineIssue] = [
    PipelineIssue(
        id="PIPE-001",
        pipeline="payment-service-ci",
        stage="dependency-scan",
        severity=Severity.CRITICAL,
        title="CVE-2021-44228 in log4j dependency",
        tool="Trivy",
        commit_sha="a1b2c3d",
        branch="main",
        detected_at="2024-11-19",
    ),
    PipelineIssue(
        id="PIPE-002",
        pipeline="auth-service-ci",
        stage="sast",
        severity=Severity.HIGH,
        title="Hardcoded JWT secret in config loader",
        tool="Semgrep",
        commit_sha="e4f5g6h",
        branch="feature/login-refactor",
        detected_at="2024-11-18",
    ),
    PipelineIssue(
        id="PIPE-003",
        pipeline="api-gateway-ci",
        stage="secret-scan",
        severity=Severity.HIGH,
        title="AWS access key committed to repository",
        tool="Gitleaks",
        commit_sha="i7j8k9l",
        branch="main",
        detected_at="2024-11-17",
    ),
    PipelineIssue(
        id="PIPE-004",
        pipeline="frontend-ci",
        stage="container-scan",
        severity=Severity.MEDIUM,
        title="Base image has 3 medium CVEs",
        tool="Trivy",
        commit_sha="m1n2o3p",
        branch="develop",
        detected_at="2024-11-16",
    ),
    PipelineIssue(
        id="PIPE-005",
        pipeline="user-service-ci",
        stage="dast",
        severity=Severity.MEDIUM,
        title="Missing Content-Security-Policy header",
        tool="OWASP ZAP",
        commit_sha="q4r5s6t",
        branch="main",
        detected_at="2024-11-15",
    ),
    PipelineIssue(
        id="PIPE-006",
        pipeline="auth-service-ci",
        stage="sast",
        severity=Severity.CRITICAL,
        title="Unvalidated redirect allows open redirect attack",
        tool="Semgrep",
        commit_sha="b3c4d5e",
        branch="main",
        detected_at="2022-03-14",
    ),
    PipelineIssue(
        id="PIPE-007",
        pipeline="payment-service-ci",
        stage="dependency-scan",
        severity=Severity.HIGH,
        title="Spring4Shell RCE in Spring Framework 5.3.17",
        tool="Trivy",
        commit_sha="f6g7h8i",
        branch="main",
        detected_at="2022-04-01",
    ),
    PipelineIssue(
        id="PIPE-008",
        pipeline="api-gateway-ci",
        stage="secret-scan",
        severity=Severity.HIGH,
        title="Plaintext database password in CI environment config",
        tool="Gitleaks",
        commit_sha="j9k0l1m",
        branch="release/v1.2",
        detected_at="2022-08-22",
    ),
]
